### ISSUE TITLE
Test skips

### ISSUE THREAD

**Issue by austinabell** [etclabscore/go-ethereum#13]
Only remaining skips are relating to https://github.com/eth-classic/go-ethereum/issues/35 (state trie clearing) and random tests [644 and 645](https://github.com/ethereum/go-ethereum/issues/15119). [EIP 684](https://github.com/ethereum/EIPs/issues/684) implementation isn't included in ETC or Atlantis upgrade so should be skipped.

```go
	// EIP 684 Implementations
	skipTests["TransactionCollisionToEmptyButCode.json"] = "Not Implemented"
	skipTests["TransactionCollisionToEmpty.json"] = "Not Implemented"
	skipTests["TransactionCollisionToEmptyButNonce.json"] = "Not Implemented"
	skipTests["CreateCollisionToEmpty.json"] = "Not Implemented"
	skipTests["CreateHashCollision.json"] = "Not Implemented"
	skipTests["createJS_ExampleContract.json"] = "Not Implemented"
	skipTests["RevertDepthCreateAddressCollision.json"] = "Not Implemented"

	// Random Test failures
	skipTests["randomStatetest644.json"] = "random unimplemented"
	skipTests["randomStatetest645.json"] = "random unimplemented"

	// EIP 158/161 skipped tests
	skipTests["RevertPrefoundEmptyOOG.json"] = "State trie clearing unimplemented"
	skipTests["FailedCreateRevertsDeletion.json"] = "State trie clearing unimplemented"
```

There is already an issue https://github.com/eth-classic/go-ethereum/issues/35 for that edge case and the others are intended so can probably close this issue now.

**Comment by steviezhang** [comment]
Test failures probably caused by how we handle dirty objects see: 
https://github.com/eth-classic/go-ethereum/issues/35#issuecomment-497475107

**Comment by austinabell** [comment]
#14 #17 #19 closes this
