### ISSUE TITLE
6.1.0 Beta Agharta Release Tracker

### ISSUE THREAD

**Issue by GregTheGreek** [etclabscore/go-ethereum#40]
- [x] Agharta config
- [x] EIP 145 Bitwise shift (#54)
- [x] EIP 1014 Create2 (#20)
- [x] EIP 1052 extCodeHash (#55)
- [ ] ~~EIP 1702~~

**Comment by soc1c** [comment]
leaving this open to see what the final ECIPs/EIPs will be

ref https://github.com/ethereumclassic/ECIPs/issues/135

will create a beta branch once this is confirmed

**Comment by soc1c** [comment]
needs an `aghartaBlock` @austinabell 

ref https://github.com/eth-classic/go-ethereum/pull/50

**Comment by soc1c** [comment]
agharta testnet block numbers

- `5_000_381` on Morden Classic Testnet (November 13, 2019)
- `301_243` on Mordor Classic Testnet (November 20, 2019)
- `1_705_549` on Kotti Classic Testnet (December 11, 2019)

https://github.com/ethereumclassic/ECIPs/pull/155/files

**Comment by austinabell** [comment]
No other config I can add other than #65, unless you want me to add Agharta to mainnet config at an arbitrarily large block number. I can add it to Mordor after your PR comes in, if you want to separate to be able to backport without it.

**Comment by soc1c** [comment]
Thanks. Didn't know we already have it. Closing this.
