### ISSUE TITLE
Geth 6.0.8/9 Windows build

### ISSUE THREAD

**Issue by peterlayke** [etclabscore/go-ethereum#52]
**EDIT problem is there is no Windows Build that I can see. Request that this be compiled and added to the assets list**

Hi all, 

Sorry to ask if this a stupid question but is there a current stable build for Windows out there? Maybe I'm missing something but after downloading I've ran into a few problems.

-geth-classic-v6.0.8-darwin.tar.gz (using 7 ZIP - I have assumed this is a windows build as the rest are marked Linux)
![image](https://user-images.githubusercontent.com/47314267/64507184-5aa84400-d31d-11e9-97ee-0cddeca8f444.png)

The I uncompressed the Zipped Zip to find this:
![image](https://user-images.githubusercontent.com/47314267/64507285-aa870b00-d31d-11e9-940e-fda436b7a897.png)

I tried renaming geth.exe files due to lacking extensions and get this:
![image](https://user-images.githubusercontent.com/47314267/64507375-f2a62d80-d31d-11e9-9e84-d4b0232e6a49.png)

I understand there is a hot-fix also but when I download that everything looks great except it's lacking geth.exe. As it is a hot fix that resolves issues with the bootnodes I guess Geth.exe wasn't needed as it is missing from this build. Can someone shed some light on what I am missing here or is this build just broken?

When I unzip the latest release you can see no geth.exe
![image](https://user-images.githubusercontent.com/47314267/64507714-cb9c2b80-d31e-11e9-83b5-01ff7a798dc2.png)

and again...
![image](https://user-images.githubusercontent.com/47314267/64507731-d787ed80-d31e-11e9-8c09-a779d4523d6a.png)

There's a hard fork coming and would like to get this resolved. I'm not a programmer and my experience with compiling is somewhat lacking so would rather avoid that if I can.

**Comment by peterlayke** [comment]
Ok, so just figured out that Darwin is a Mac build. It seems there is no Windows build out there. Can anyone confirm?

**Comment by soc1c** [comment]
yeah, we don't have any proper builds. just use parity-ethereum or multi-geth which both should come with releases for windows.

**Comment by austinabell** [comment]
There is a windows binary and sha on the 6.0.9 version: https://github.com/etclabscore/go-ethereum/releases/tag/v6.0.9 , I have generated an updated windows build that is a zip file, but it hasn't been retroactively replaced in the 6.0.9 version but can come in the next release.

Edit: I see you unpacked the mac tarball so hopefully this works for you, but let me know if it doesn't.

**Comment by innovative-sol** [comment]
Hi! Same issue. I downloaded the Windows archive, there is a SHA256 file for geth.exe but the geth.exe file itself is missing. Is there any Windows update available? Thanks!

**Comment by austinabell** [comment]
> Hi! Same issue. I downloaded the Windows archive, there is a SHA256 file for geth.exe but the geth.exe file itfels is missing. Is there any Windows update available? Thanks!

My apologies, you are right, not sure how that happened. I will look into updating that later today

**Comment by innovative-sol** [comment]
> > Hi! Same issue. I downloaded the Windows archive, there is a SHA256 file for geth.exe but the geth.exe file itfels is missing. Is there any Windows update available? Thanks!
> 
> My apologies, you are right, not sure how that happened. I will look into updating that later today

No problem. I really hope the new version will be able to catch up and update faster. Since this morning the older release is syncing very slowly and right now is about 6.400 blocks behind. :(

**Comment by tanderbold** [comment]
Hi! There is not a geth.exe in archive now (

**Comment by play0** [comment]
@tanderbold Thanks for sorting this.

**Comment by play0** [comment]
@tanderbold I used Muti-Geth as @soc1c suggested. This has worked for me.

**Comment by tanderbold** [comment]
> @tanderbold I used Muti-Geth as @soc1c suggested. This has worked for me.

thanks a lot

**Comment by austinabell** [comment]
Yeah I can't update the binary for that release but a correct windows binary should come in the next release

**Comment by guotie** [comment]
please fix it

**Comment by soc1c** [comment]
Please use multi-geth or parity-ethereum if you require windows binaries.

- https://github.com/multi-geth/multi-geth/releases
- https://github.com/paritytech/parity-ethereum/releases
