### ISSUE TITLE
can't sync data using morden test chain

### ISSUE THREAD

**Issue by ivan-lingf** [etclabscore/go-ethereum#63]
I can't sync data using morden test chain.
The log file print message:  p2p/discover/table.go:439] no seed nodes found

**Comment by soc1c** [comment]
morden testnet is deprecated. please use mordor instead.

https://github.com/eth-classic/mordor/

**Comment by soc1c** [comment]
ref #57

**Comment by soc1c** [comment]
Please, also consider migrating to Multi Geth or Parity Ethereum as this client will be soft-landed soon.
