### ISSUE TITLE
Not synchronized

### ISSUE THREAD

**Issue by XMR888** [etclabscore/go-ethereum#69]
i7-4770
32GB RAM
512 GB SSD
1Gbit network

wait +/- 5 days - Sync not completed, after restart "knownStates" - 0.

I don’t understand what is happening with this geth version. 
Old version synced normally.
How to synchronize it?

**Comment by soc1c** [comment]
Please use Parity Ethereum, Hyperledger Besu, or Multi-Geth if you experience issues with Geth Classic.
