### ISSUE TITLE
i don't upgrade etc node,but it can normally sync data. my version is v6.0.9

### ISSUE THREAD

**Issue by Sallery-X** [etclabscore/go-ethereum#72]

**Comment by tzdybal** [comment]
It seems that new opcodes enabled by latest hardfork was not used yet.
As soon as any contract executes one of the new instructions, your node should have consensus error.

**Comment by Sallery-X** [comment]
this hard fork make me so hard to upgrade and cherry-pick on https://github.com/jdcloud-bds/bds-etc/commits/v6.0.9-bds

**Comment by soc1c** [comment]
there will be no further releases for this client. please migrate to besu, parity, or multi-geth.
